const title_name = document.querySelector(".title-name");
const book_name = document.querySelector(".book-name");

const adj1 = [
    "Dark",
    "Heavy",
    "Gilded",
    "Iron",
    "Steel",
    "Golden",
    "Gleaming",
    "Fraught",
    "Cursed",
    "Silent",
    "Jade",
    "Emerald",
    "Diamond",
    "Wooden",
    "Burning",
    "Flaming",
    "Vengeful",
    "Careful",
    "Cautious",
    "Hasty",
    "Dead",
    "Living",
    "Last",
    "Final",
    "First",
    "Late",
    "Crystal",
    "Shining",
    "Tarnished",
    "Greedy",
    "Sputtering",
]
const noun1 = [
    "Tower",
    "Hall",
    "City",
    "Citadel",
    "Crown",
    "King",
    "Prince",
    "Princess",
    "Hero",
    "Queen",
    "Throne",
    "Cliff",
    "River",
    "Quill",
    "Sword",
    "Staff",
    "Wizard",
    "Wolf",
    "Flame",
    "Torch",
    "Legend",
    "Thief",
    "Tree",
    "Rock",
    "Stone",
    "Knight",
    "Emperor",
    "Samurai",
    "Wall",
    "Key",
    "Keyhole",
    "Lock",
    "Door",
    "Hand",
    "Foot",
]
const noun2 = [
    "Dance",
    "Battle",
    "Feast",
    "Prince",
    "Sword",
    "Crown",
    "Game",
    "Life",
    "Scepter",
    "Castle",
    "Fortress",
    "Field",
    "Pit",
    "Forest",
    "Cavern",
    "Mountain",
    "Waterfall",
    "Tome",
    "War",
    "Night",
    "Way",
    "Deception",
    "Sea",
    "River",
    //"Age",
    //"Era",
    "Name",
    "Child",
    "World",
    "Story",
    "Tale",
    "Poem",
    "Fable",
    "Color",
    "Sound",
    "Smell",
    "Glint",
    "Glimpse",
    "King",
    "Queen",
    "Legend",
    "Master",
    "Fist",
    "Rhythm",
]
const noun3 = [
    "Dragons",
    "Kings",
    "Thorns",
    "Gold",
    "Ashes",
    "Ash",
    "Steel",
    "Stone",
    "Stones",
    "Pain",
    "Power",
    "Life",
    "Fire",
    "Water",
    "Air",
    "Earth",
    "Snakes",
    "Wolves",
    "Horses",
    "Love",
    "Death",
    "Hatred",
    "Wind",
    "Truth",
    "Deception",
    "Blood",
    "Gods",
    "Heroes",
    "Men",
    "Warriors",
    "Time",
    "Empires",
    "Rage",
    "Vengance",
    "the Sky",
    "Darkness",
    "the Deep",
    "the Heavens",
    "Embers",
    "Knights",
    "Revenge",
]

function generate_move() {
    const word1 = adj1[Math.floor(Math.random() * adj1.length)];

    const word2 = noun1[Math.floor(Math.random() * noun1.length)];

    const book_num = 1 + Math.floor(Math.random()*9);

    const word3 = noun2[Math.floor(Math.random() * noun2.length)];

    const word4 = noun3[Math.floor(Math.random() * noun3.length)];
    
    const title = `The ${word1} ${word2}`
    const book = `Book ${book_num}: A ${word3} of ${word4}`
    
    title_name.innerHTML = title;
    book_name.innerHTML = book;
}